### ISSUE TITLE
Notice on fake contributions

### ISSUE THREAD

**Issue by gitpoliceofindia** [HRithIkGowDA/HRithIkGowDA#6]
### Hi @HRithIkGowDA,

# We can see that you are just removing and adding a full stop (.) character to make it seem like you are coding everyday.
### Please refrain from such activities.

Your contributions are public, it will reflect poorly on your character.

We have a full archive of your *fake* contributions at - https://web.archive.org/web/20230906051550/https://github.com/HRithIkGowDA/HRithIkGowDA/commits/main

Thanks,
Git Police of India

**Comment by HRithIkGowDA** [comment]
get lost, fake account
